<!--
2021-06-07
데이콘 경진 대회 1등 솔루션
KBO 타자 OPS 예측
-->

# Dacon study with textbook 1
2021-06-07
<br><br>




### KBO 타자 OPS 예측
<hr>




<strong>분석 시 주의 사항 :</strong>
<li><b>분석논리</b>가 실제 데이터에서 <b>제대로 적용이 되는지</b> 확인</li>
<li><b>도메인 지식</b>에 데이터 분석 지식을 결합할 것</li>
<li>컬럼이 많은 경우 과적합을 피하기 위해 가능한 <b>단순화한 정보</b>만으로 머신러닝 진행하는 것도 하나의 방법</li>
<li><b>분력 전략</b>을 잘 세우는 것이 중요</li>
<li><b>인사이트를 도출</b>하는 과정 중요. 이 과정이 생략되거나 잘못되면 모델학습 이상은 이루어지기 힘들 수 있음</li>
<li>인사이트를 통해 <b>필요한 정보만을 잘 추출하여 학습을 진행</b>해야함</li>
<hr>




<h5><b>KBO 타자 OPS 예측 경진대회</b></h5>
<b>문제유형</b> : Time-Series(시계열), Regression(회귀)<br>
<b>평가척도</b> : WRMSE<br>
<b>대회기간</b> : 2019.02.08~2019.07.18<br>
<b>경진대회 배경 요약</b>:<br>
<p>특정 선수의 성적 변동성이 해마다 크기 때문에 내년 성적을 예측하기 어려움<br>
본 대회 개최 목적은는 야구데이터로 불확실성 문제를 해결하기 위함임<br>
2019년 타자들의 상반기 성적 예측을 목표로 함<br>
</p>
<b>대회 내용</b> :
<p>2019년 타자들의 상반기 OPS를 예측하는 모델 제작<br>
2010년부터 1군 엔트리에 1번 이상 포함되었던 타자들의 역대 정규시즌, 시범경기 성적정보 제공</p>
<hr>




<h5><b>WRMSE?</b></h5>
Weighted Root Mean Square Error<br>
평가 척도 방식 중 하나
$$WRMSE = \sum_{i=1}^{n}\sqrt{\frac{(y_i-\hat{y}_i)^2\ w_i}{\sum{w_i}}}$$
$$y = 실제값\ (실제\ OPS),\ \hat{y} = 예측값\ (예측된\ OPS),\ w_i = 가중치\ (타수)$$
$$Error = y-\hat{y}$$
<p>최종적으로는 에러가 적을 수록 좋기 때문에 WRMSE의 값을 낮추는 것이 목적<br>
즉, 타수가 낮은 선수는 타수가 높은 선수에 비하여 WRMSE에 적은 영향을 주므로, 타수가 높은 선수의 예측을 잘해야 함</p>
<hr>




<h5><b>도메인 조사</b></h5>
<p>좋은 예측값을 출력하기 위해서는 도매인 지식이 중요함<br>
이 데이터에서는 프로야구에 대한 지식이 도메인 지식</p><br>

<h5><b>프로야구 도메인 지식</b></h5>
<p><b>시범경기, 정규시즌</b></p>
<ul><b>정규시즌</b>
  <li>프로스포츠 경기. 정규시즌에서의 성적이 쌓여 각 <b>구단의 최종 순위 결정</b></li>
  <li><b>타자의 OPS가 정규시즌의 성적</b></li>
</ul>
<ul><b>시범경기</b>
  <li>정규시즌 시작 전 열리는 <b>비공식 경기</b></li>
  <li>최종 순위에 영향 미치지 않으며 단순히 <b>연습의 의미</b>만 있음</li>
  <li>시합 자체는 정규시즌과 동일한 방식으로 진행</li>
</ul>
<p><b>상반기, 하반기</p></b>
<li>상반기 이후 짧은 휴식기를 가지고 하반기 정규시즌 진행</li>
<li>매년 기준이 조금씩 다름</li>
<li>2019년은 7월 18일까지를 상반기로 정의하고 있음</li><br>
<p><b>주요 야구 용어</b></p>
<li>OBP(On Base Percentage) : 출루율. 타수 대비 아웃되지 않고 1루로 출루한 비율</li>
<li>SLG(Slugging Percentage) : 장타율. 타수에서 기대되는 평균 루타</li>
<li>OPS(On base Plus Slugging) : 출류율 + 장타율</li>
<li>AB(At Bat) : 타수. 타자가 정규로 타격을 완료한 횟수</li>
<li>BB(Base on Ball) : 볼넷</li>
<li>HBP(Hit By Pitch) : 투수가 던진 공에 맞아 출루</li>
<li>SF(Sacrifice Fly) : 타자 본인은 아웃지만 주자를 진루시켜준 경우</li>
<li>AVG(Batting Average) : 타율. 타수 대비 안타비율</li>
<li>1B, 2B, 3B : 1루타, 2루타, 3루타. 한 번의 안타로 몇 루까지 진출했는지 표시</li>
<li>HR, H : 홈런, 안타</li>
<hr>




